#! /usr/bin/env python
#coding=utf-8

'''
给定一个整数数组nums和一个目标值target,在该数组中找出和为目标值的两个整数，返回数组下标。
假设每种输入只会对应一个答案。但不能重复利用数组中同样的元素。

示例：
给定 nums=[2,7,11,15] target=9
因为 nums[0]+nums[1]=2+7=9
所以返回[0,1]
'''

def two_nums_sum(nums,target):
    hashmap={}
    for i,num in enumerate(nums):
        if hashmap.get(target - num) is not None:
            return [hashmap.get(target - num),i]
        hashmap[num] = i #先判断if，如果if不成立再把这个数字加入字典，等着下次用。

    print('没有答案')

nums = [2,2,1,1,11,4,4,15,2]
target=8
re = two_nums_sum(nums,target)
print(re)